[package]
name = "cc-seed"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { workspace = true }
worker-macros = { workspace = true }
getrandom = { version = "0.3", features = ["wasm_js"] }
card-confluence-db = { path = "../../packages/card_confluence_db" }
cloudflare-utils = { path = "../../packages/cloudflare_utils" }
object_store = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
