// Generated by https://quicktype.io

export interface IScryfallSetResult {
    object: string;
    has_more: boolean;
    data: Datum[];
}

export interface Datum {
    object: Object;
    id: string;
    code: string;
    name: string;
    uri: string;
    scryfall_uri: string;
    search_uri: string;
    released_at: Date;
    set_type: SetType;
    card_count: number;
    parent_set_code?: string;
    digital: boolean;
    nonfoil_only: boolean;
    foil_only: boolean;
    icon_svg_uri: string;
    tcgplayer_id?: number;
    mtgo_code?: string;
    arena_code?: string;
    block_code?: string;
    block?: string;
    printed_size?: number;
}

export enum Object {
    Set = 'set',
}

export enum SetType {
    Alchemy = 'alchemy',
    Archenemy = 'archenemy',
    Arsenal = 'arsenal',
    Box = 'box',
    Commander = 'commander',
    Core = 'core',
    DraftInnovation = 'draft_innovation',
    DuelDeck = 'duel_deck',
    Expansion = 'expansion',
    FromTheVault = 'from_the_vault',
    Funny = 'funny',
    Masterpiece = 'masterpiece',
    Masters = 'masters',
    Memorabilia = 'memorabilia',
    Minigame = 'minigame',
    Planechase = 'planechase',
    PremiumDeck = 'premium_deck',
    Promo = 'promo',
    Spellbook = 'spellbook',
    Starter = 'starter',
    Token = 'token',
    TreasureChest = 'treasure_chest',
    Vanguard = 'vanguard',
}
