// Generated by https://quicktype.io

export interface IScryfallSymbolResult {
    object: string;
    has_more: boolean;
    data: IScryfallSymbol[];
}

export interface IScryfallSymbol {
    object: Object;
    symbol: string;
    svg_uri: string;
    loose_variant: null | string;
    english: string;
    transposable: boolean;
    represents_mana: boolean;
    appears_in_mana_costs: boolean;
    mana_value: number | null;
    hybrid: boolean;
    phyrexian: boolean;
    cmc: number | null;
    funny: boolean;
    colors: Color[];
    gatherer_alternates: string[] | null;
}

export interface ISymbolMap {
    [key: string]: {
        uri: string;
        description: string;
    };
}

enum Color {
    B = 'B',
    G = 'G',
    R = 'R',
    U = 'U',
    W = 'W',
}

enum Object {
    CardSymbol = 'card_symbol',
}
