name = "workflow-seed"
# main = "build/index.js"
main = "src/index.ts"
compatibility_date = "2026-04-12"

[[r2_buckets]]
binding = "cc_parquet_latest"
bucket_name = "cc-parquet-latest"

[[r2_buckets]]
bucket_name = "cc-parquet-history"
binding = "cc_parquet_history"

[[workflows]]
name = "workflow-seed"
binding = "workflow_seed"
class_name = "WorkflowSeed"
