// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {scanQueryContent} from "./tokens"
const spec_identifier = {__proto__:null,domain:70, tag:72, group:74, view:76}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*OQYQQOOOOQO'#Ca'#CaOhQQO'#C`OOQO'#Cf'#CfOmQQO'#CeOOQO'#Co'#CoOmQQO'#CnOOQO'#Ct'#CtOmQQO'#CsOOQO'#C_'#C_OOQO'#Cv'#CvQYQQOOOrQRO,58zOOQO'#Cg'#CgOwQQO,59PO!PQQO,59YO![QQO,59_OOQO-E6t-E6tOOQO'#Cc'#CcO!dQQO1G.fO!iQQO'#ChO!qQRO1G.kO!yQQO1G.kO#OQQO1G.tO#^QQO1G.tO#lQQO1G.tO#tQQO1G.yO$SQQO1G.yOOQO7+$Q7+$QO$XQQO'#CjOOQO,59S,59SO$^QQO,59SOOQO7+$V7+$VO$fQQO7+$VO$kQRO7+$VOOQO'#Cq'#CqO$sQQO'#CxO%XQQO7+$`OOQO7+$`7+$`O%gQQO7+$`O%XQQO7+$`O%gQQO7+$`OOQO'#Cu'#CuO%uQQO'#CyO&WQQO7+$eOOQO7+$e7+$eO&WQQO7+$eOmQQO,59UOmQQO'#CwO&fQQO1G.nOOQO1G.n1G.nOOQO<<Gq<<GqO&nQQO<<GqOOQO,59d,59dOOQO-E6v-E6vOOQO<<Gz<<GzO&sQQO<<GzO'RQQO<<GzOOQO,59e,59eOOQO-E6w-E6wOOQO<<HP<<HPO'aQQO<<HPOOQO1G.p1G.pOOQO,59c,59cOOQO-E6u-E6uOOQO7+$Y7+$YOOQOAN=]AN=]OOQOAN=fAN=fOOQOAN=kAN=k",
  stateData: "'o~OqOSPOS~OsPOtROuTOvVO~OU[O~Or]O~OobO~OUeO]dO~OUhO]dOdgO~O]dOdjO~OWlO~OanOr]O~OWpOobO~OUrO~OfvOr]OtROuTO~OWvOr]OtROuTO~OUyOdxO~Of}Or]OtROuTO~Od!OO~O_!PO~O`!QOa!SO~OW!TO~OW!TOobO~O`!VOflXrlXtlXulXWlX~Of!XOr]OtROuTO~OW!XOr]OtROuTO~O`![OfmXrmXtmXumX~Of!^Or]OtROuTO~O`!QOa!cO~OW!dO~Of!eOr]OtROuTO~OW!eOr]OtROuTO~Of!fOr]OtROuTO~O",
  goto: "%knPPPoswP{P!U!j!z#lP#uPPP!U#{P$]Ps$g$k$q$w$}%aTYOZTXOZTQOZQc[QqeR!UrSXOZ`sghuwxy!Y!ZXzj|!O!_mSOZghjuwxy|!O!Y!Z!_Q^SQ_UQ`WSmd!Q`sghuwxy!Y!ZWzj|!O!_R!`!PQf^Qi_Rk`QodR!a!QmUOZghjuwxy|!O!Y!Z!_atghuwxy!Y!ZTWOZX{j|!O!_QZORaZQ!RoR!b!RQugQwhW!Wuw!Y!ZQ!YxR!ZyQ|jS!]|!_R!_!O",
  nodeNames: "⚠ LineComment Program Statement DomainDefinition DomainKeyword [ Query ] TagDefinition TagKeyword Identifier Params ( ParamItem : , ) GroupDefinition GroupKeyword { GroupItem } ViewDefinition ViewKeyword ViewItem",
  maxTerm: 38,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "$c~RaXY!WYZ!W]^!Wpq!Wst!ixy#Tyz#Y|}#_}!O#d![!]#x!c!}#d!}#O#}#P#Q$S#R#S#d#T#o#d#o#p$X#q#r$^~!]Sq~XY!WYZ!W]^!Wpq!W~!nTP~O#O!i#P#b!i#c;'S!i;'S;=`!}<%lO!i~#QP;=`<%l!i~#YO]~~#_Oa~~#dO`~~#iTr~}!O#d!Q![#d!c!}#d#R#S#d#T#o#d~#}O_~~$SOU~~$XOW~~$^Od~~$cOf~",
  tokenizers: [scanQueryContent, 0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 34, get: (value: keyof typeof spec_identifier) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
