// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,order:10, sort:10, dir:10, direction:10, unique:10, prefer:10, NOT:38, AND:44, OR:48}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hQ`QPOOOOQO'#C`'#C`OOQO'#C_'#C_OqQPO'#C_O!uQPO'#C^OOQO'#DO'#DOOOQO'#Cn'#CnOOQO'#C}'#C}O`QPO'#C}OOQO'#C|'#C|O#^QPO'#C{Q#nQPOOO`QPO'#CmOOQO'#Cb'#CbO#sQPO,58xOOQO,59i,59iOOQO'#Cq'#CqO`QPO,59hOOQO,59h,59hOOQO'#Cs'#CsO`QPO,59gO#{QPO,59XOOQO'#Cj'#CjOOQO1G.d1G.dOOQO1G/S1G/SO$TQPO1G/ROOQO1G.s1G.s",
  stateData: "$e~OkOSlOSmOSnOS~OTPOcUOdWOsROt[O~OT`XVRXWRXXRXYRXZRX[RX]RXc`Xd`Xf`Xh`Xi`Xs`Xt`Xu`X~OV]OW]OX]OY]OZ]O[]O]]O~Of`OhoXioXuoX~P`OhcO~O_fOsfO~OhcOujO~Of`Ohoiioiuoi~P`O",
  goto: "#osPPt}!WP!aPPPPPPP!dPtt!gPP!pP!tPPPPPPP!x#O#V#f_TOWY[adi_SOWY[adi_QOWY[adiR^SRg^_WOWY[adiTaYiTdZeQZORe[SYO[RidUXO[dQ_WSbYiRha_VOWY[adi",
  nodeNames: "⚠ Query Predicate FieldName GlobalField GlobalField Operator Colon Eq Ne Lte Lt Gte Gt Value QuotedString BareWord Group Not Not NotOp And And Or Or",
  maxTerm: 37,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "&h~RdXY!aYZ!f]^!kpq!pqr!urs#Qxy$tyz$yz{%O}!O%m!O!P%O!P!Q%O!Q![%O![!]%r!^!_%w!_!`&U!`!a&Z!c!}%O#R#S%O#T#o%O~!fOl~~!kOn~~!pOm~~!uOk~~!xP!_!`!{~#QOX~~#TWOY#QZr#Qrs#ms#O#Q#O#P#r#P;'S#Q;'S;=`$n<%lO#Q~#rO_~~#uRO;'S#Q;'S;=`$O;=`O#Q~$RXOY#QZr#Qrs#ms#O#Q#O#P#r#P;'S#Q;'S;=`$n;=`<%l#Q<%lO#Q~$qP;=`<%l#Q~$yOt~~%OOu~~%TWs~z{%O}!O%O!O!P%O!P!Q%O!Q![%O!c!}%O#R#S%O#T#o%O~%rOd~~%wOV~~%|PZ~!_!`&P~&UOY~~&ZOW~~&`P]~!_!`&c~&hO[~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 35, get: (value: keyof typeof spec_identifier) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
