pub const KEYWORDS: &[&str] = &[
    "name",
    "n",
    "type",
    "t",
    "oracle",
    "o",
    "mana",
    "m",
    "power",
    "pow",
    "toughness",
    "tou",
    "loyalty",
    "loy",
    "defense",
    "def",
    "edhrec",
    "penny",
    "powtou",
    "pt",
    "artist",
    "a",
    "flavor",
    "ft",
    "watermark",
    "wm",
    "border",
    "frame",
    "layout",
    "stamp",
    "color",
    "c",
    "identity",
    "ci",
    "id",
    "cmc",
    "mv",
    "manavalue",
    "number",
    "cn",
    "rarity",
    "r",
    "settype",
    "st",
    "format",
    "f",
    "legal",
    "is",
    "in",
    "game",
    "lang",
    "l",
    "scryfallid",
    "oracleid",
    "produces",
    "oracle_tag",
    "otag",
    "keyword",
    "kw",
    "set",
    "s",
    "edition",
    "e",
    "year",
    "date",
];

pub const IS_VALUES: &[&str] = &[
    "legendary",
    "nonlegendary",
    "land",
    "creature",
    "artifact",
    "enchantment",
    "planeswalker",
    "battle",
    "spell",
    "permanent",
    "reprint",
    "firstprinting",
    "booster",
    "promo",
    "digital",
    "oversized",
    "story_spotlight",
    "textless",
    "full_art",
    "reserved",
    "foil",
    "nonfoil",
    "etched",
    "commander",
];

// pub const FORMATS: &[&str] = &[
//     "standard",
//     "future",
//     "historic",
//     "timeless",
//     "gladiator",
//     "pioneer",
//     "explorer",
//     "modern",
//     "legacy",
//     "pauper",
//     "vintage",
//     "penny",
//     "commander",
//     "oathbreaker",
//     "standardbrawl",
//     "brawl",
//     "alchemy",
//     "paupercommander",
//     "duel",
//     "oldschool",
//     "premodern",
//     "predh",
// ];
